#!/bin/bash

if [ -z "$1" ] || [ -z "$2" ]; then
    echo "Usage: $s <svn mirror dir> <likewise-open git branch>"
    exit 1
fi


GITSVNDIR="$1"
GITBRANCH="$2"

if [ ! -d "${GITSVNDIR}" ]; then
    echo "${GITSVNDIR} is not a directory."
    exit 1
fi

for d in ${GITSVNDIR}/*; do
    if [ -d $d/.git ]; then
	echo $d
	(cd $d && git clean -d -x -f ) || exit 1
	diff -uBbrN --exclude=.git ${GITBRANCH}/`basename $d`/ $d/ > `basename $d`.patch
	[ ! -s `basename $d`.patch ] && /bin/rm `basename $d`.patch
    fi
done
